In [1]:
! pip install tensorflow

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: tensorflow in c:\users\user\appdata\roaming\python\python313\site-packages (2.21.0)
Requirement already satisfied: absl-py>=1.0.0 in c:\users\user\appdata\roaming\python\python313\site-packages (from tensorflow) (2.5.0)
Requirement already satisfied: astunparse>=1.6.0 in c:\users\user\appdata\roaming\python\python313\site-packages (from tensorflow) (1.6.3)
Requirement already satisfied: flatbuffers>=25.9.23 in c:\users\user\appdata\roaming\python\python313\site-packages (from tensorflow) (25.12.19)
Requirement already satisfied: gast!=0.5.0,!=0.5.1,!=0.5.2,>=0.2.1 in c:\users\user\appdata\roaming\python\python313\site-packages (from tensorflow) (0.7.0)
Requirement already satisfied: google_pasta>=0.1.1 in c:\users\user\appdata\roaming\python\python313\site-packages (from tensorflow) (0.2.0)
Requirement already satisfied: libclang>=13.0.0 in c:\users\user\appdata\roaming\python\python313\site-packages (from tensorflow) (18.1.1)
Requirement already satisfied: opt_einsum>=2.3.2 in c:\users\user\appdata\roaming\python\python313\site-packages (from tensorflow) (3.4.0)
Requirement already satisfied: packaging in c:\programdata\anaconda3\lib\site-packages (from tensorflow) (25.0)
Requirement already satisfied: protobuf<8.0.0,>=6.31.1 in c:\users\user\appdata\roaming\python\python313\site-packages (from tensorflow) (7.35.1)
Requirement already satisfied: requests<3,>=2.21.0 in c:\programdata\anaconda3\lib\site-packages (from tensorflow) (2.32.5)
Requirement already satisfied: setuptools in c:\programdata\anaconda3\lib\site-packages (from tensorflow) (80.9.0)
Requirement already satisfied: six>=1.12.0 in c:\programdata\anaconda3\lib\site-packages (from tensorflow) (1.17.0)
Requirement already satisfied: termcolor>=1.1.0 in c:\users\user\appdata\roaming\python\python313\site-packages (from tensorflow) (3.3.0)
Requirement already satisfied: typing_extensions>=3.6.6 in c:\programdata\anaconda3\lib\site-packages (from tensorflow) (4.15.0)
Requirement already satisfied: wrapt>=1.11.0 in c:\programdata\anaconda3\lib\site-packages (from tensorflow) (1.17.0)
Requirement already satisfied: grpcio<2.0,>=1.24.3 in c:\users\user\appdata\roaming\python\python313\site-packages (from tensorflow) (1.82.1)
Requirement already satisfied: keras>=3.12.0 in c:\users\user\appdata\roaming\python\python313\site-packages (from tensorflow) (3.15.0)
Requirement already satisfied: numpy>=1.26.0 in c:\programdata\anaconda3\lib\site-packages (from tensorflow) (2.3.5)
Requirement already satisfied: h5py<3.15.0,>=3.11.0 in c:\users\user\appdata\roaming\python\python313\site-packages (from tensorflow) (3.14.0)
Requirement already satisfied: ml_dtypes<1.0.0,>=0.5.1 in c:\users\user\appdata\roaming\python\python313\site-packages (from tensorflow) (0.5.4)
Requirement already satisfied: charset_normalizer<4,>=2 in c:\programdata\anaconda3\lib\site-packages (from requests<3,>=2.21.0->tensorflow) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in c:\programdata\anaconda3\lib\site-packages (from requests<3,>=2.21.0->tensorflow) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\programdata\anaconda3\lib\site-packages (from requests<3,>=2.21.0->tensorflow) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in c:\programdata\anaconda3\lib\site-packages (from requests<3,>=2.21.0->tensorflow) (2026.5.20)
Requirement already satisfied: wheel<1.0,>=0.23.0 in c:\programdata\anaconda3\lib\site-packages (from astunparse>=1.6.0->tensorflow) (0.45.1)
Requirement already satisfied: rich in c:\programdata\anaconda3\lib\site-packages (from keras>=3.12.0->tensorflow) (14.2.0)
Requirement already satisfied: namex in c:\users\user\appdata\roaming\python\python313\site-packages (from keras>=3.12.0->tensorflow) (0.1.0)
Requirement already satisfied: optree in c:\users\user\appdata\roaming\python\python313\site-packages (from keras>=3.12.0->tensorflow) (0.19.1)
Requirement already satisfied: markdown-it-py>=2.2.0 in c:\programdata\anaconda3\lib\site-packages (from rich->keras>=3.12.0->tensorflow) (2.2.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in c:\programdata\anaconda3\lib\site-packages (from rich->keras>=3.12.0->tensorflow) (2.19.2)
Requirement already satisfied: mdurl~=0.1 in c:\programdata\anaconda3\lib\site-packages (from markdown-it-py>=2.2.0->rich->keras>=3.12.0->tensorflow) (0.1.2)

In [2]:
!python --version

Python 3.13.9

In [3]:
!pip uninstall tensorflow-gpu -y

WARNING: Skipping tensorflow-gpu as it is not installed.

In [4]:
!pip install --upgrade pip

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: pip in c:\programdata\anaconda3\lib\site-packages (25.3)
Collecting pip
  Using cached pip-26.2.1-py3-none-any.whl.metadata (4.6 kB)
Using cached pip-26.2.1-py3-none-any.whl (1.8 MB)

ERROR: To modify pip, please run the following command:
C:\ProgramData\anaconda3\python.exe -m pip install --upgrade pip

In [5]:
!pip install tensorflow

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: tensorflow in c:\users\user\appdata\roaming\python\python313\site-packages (2.21.0)
Requirement already satisfied: absl-py>=1.0.0 in c:\users\user\appdata\roaming\python\python313\site-packages (from tensorflow) (2.5.0)
Requirement already satisfied: astunparse>=1.6.0 in c:\users\user\appdata\roaming\python\python313\site-packages (from tensorflow) (1.6.3)
Requirement already satisfied: flatbuffers>=25.9.23 in c:\users\user\appdata\roaming\python\python313\site-packages (from tensorflow) (25.12.19)
Requirement already satisfied: gast!=0.5.0,!=0.5.1,!=0.5.2,>=0.2.1 in c:\users\user\appdata\roaming\python\python313\site-packages (from tensorflow) (0.7.0)
Requirement already satisfied: google_pasta>=0.1.1 in c:\users\user\appdata\roaming\python\python313\site-packages (from tensorflow) (0.2.0)
Requirement already satisfied: libclang>=13.0.0 in c:\users\user\appdata\roaming\python\python313\site-packages (from tensorflow) (18.1.1)
Requirement already satisfied: opt_einsum>=2.3.2 in c:\users\user\appdata\roaming\python\python313\site-packages (from tensorflow) (3.4.0)
Requirement already satisfied: packaging in c:\programdata\anaconda3\lib\site-packages (from tensorflow) (25.0)
Requirement already satisfied: protobuf<8.0.0,>=6.31.1 in c:\users\user\appdata\roaming\python\python313\site-packages (from tensorflow) (7.35.1)
Requirement already satisfied: requests<3,>=2.21.0 in c:\programdata\anaconda3\lib\site-packages (from tensorflow) (2.32.5)
Requirement already satisfied: setuptools in c:\programdata\anaconda3\lib\site-packages (from tensorflow) (80.9.0)
Requirement already satisfied: six>=1.12.0 in c:\programdata\anaconda3\lib\site-packages (from tensorflow) (1.17.0)
Requirement already satisfied: termcolor>=1.1.0 in c:\users\user\appdata\roaming\python\python313\site-packages (from tensorflow) (3.3.0)
Requirement already satisfied: typing_extensions>=3.6.6 in c:\programdata\anaconda3\lib\site-packages (from tensorflow) (4.15.0)
Requirement already satisfied: wrapt>=1.11.0 in c:\programdata\anaconda3\lib\site-packages (from tensorflow) (1.17.0)
Requirement already satisfied: grpcio<2.0,>=1.24.3 in c:\users\user\appdata\roaming\python\python313\site-packages (from tensorflow) (1.82.1)
Requirement already satisfied: keras>=3.12.0 in c:\users\user\appdata\roaming\python\python313\site-packages (from tensorflow) (3.15.0)
Requirement already satisfied: numpy>=1.26.0 in c:\programdata\anaconda3\lib\site-packages (from tensorflow) (2.3.5)
Requirement already satisfied: h5py<3.15.0,>=3.11.0 in c:\users\user\appdata\roaming\python\python313\site-packages (from tensorflow) (3.14.0)
Requirement already satisfied: ml_dtypes<1.0.0,>=0.5.1 in c:\users\user\appdata\roaming\python\python313\site-packages (from tensorflow) (0.5.4)
Requirement already satisfied: charset_normalizer<4,>=2 in c:\programdata\anaconda3\lib\site-packages (from requests<3,>=2.21.0->tensorflow) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in c:\programdata\anaconda3\lib\site-packages (from requests<3,>=2.21.0->tensorflow) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\programdata\anaconda3\lib\site-packages (from requests<3,>=2.21.0->tensorflow) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in c:\programdata\anaconda3\lib\site-packages (from requests<3,>=2.21.0->tensorflow) (2026.5.20)
Requirement already satisfied: wheel<1.0,>=0.23.0 in c:\programdata\anaconda3\lib\site-packages (from astunparse>=1.6.0->tensorflow) (0.45.1)
Requirement already satisfied: rich in c:\programdata\anaconda3\lib\site-packages (from keras>=3.12.0->tensorflow) (14.2.0)
Requirement already satisfied: namex in c:\users\user\appdata\roaming\python\python313\site-packages (from keras>=3.12.0->tensorflow) (0.1.0)
Requirement already satisfied: optree in c:\users\user\appdata\roaming\python\python313\site-packages (from keras>=3.12.0->tensorflow) (0.19.1)
Requirement already satisfied: markdown-it-py>=2.2.0 in c:\programdata\anaconda3\lib\site-packages (from rich->keras>=3.12.0->tensorflow) (2.2.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in c:\programdata\anaconda3\lib\site-packages (from rich->keras>=3.12.0->tensorflow) (2.19.2)
Requirement already satisfied: mdurl~=0.1 in c:\programdata\anaconda3\lib\site-packages (from markdown-it-py>=2.2.0->rich->keras>=3.12.0->tensorflow) (0.1.2)

In [6]:
import tensorflow as tf

print("TensorFlow version:", tf.__version__)
print("GPUs:", tf.config.list_physical_devices('GPU'))

TensorFlow version: 2.21.0
WARNING:tensorflow:TensorFlow GPU support is not available on native Windows for TensorFlow >= 2.11. Even if CUDA/cuDNN are installed, GPU will not be used. Please use WSL2 or the TensorFlow-DirectML plugin.
GPUs: []

In [7]:
!pip uninstall tensorflow-gpu -y
!pip install tensorflow

WARNING: Skipping tensorflow-gpu as it is not installed.

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: tensorflow in c:\users\user\appdata\roaming\python\python313\site-packages (2.21.0)
Requirement already satisfied: absl-py>=1.0.0 in c:\users\user\appdata\roaming\python\python313\site-packages (from tensorflow) (2.5.0)
Requirement already satisfied: astunparse>=1.6.0 in c:\users\user\appdata\roaming\python\python313\site-packages (from tensorflow) (1.6.3)
Requirement already satisfied: flatbuffers>=25.9.23 in c:\users\user\appdata\roaming\python\python313\site-packages (from tensorflow) (25.12.19)
Requirement already satisfied: gast!=0.5.0,!=0.5.1,!=0.5.2,>=0.2.1 in c:\users\user\appdata\roaming\python\python313\site-packages (from tensorflow) (0.7.0)
Requirement already satisfied: google_pasta>=0.1.1 in c:\users\user\appdata\roaming\python\python313\site-packages (from tensorflow) (0.2.0)
Requirement already satisfied: libclang>=13.0.0 in c:\users\user\appdata\roaming\python\python313\site-packages (from tensorflow) (18.1.1)
Requirement already satisfied: opt_einsum>=2.3.2 in c:\users\user\appdata\roaming\python\python313\site-packages (from tensorflow) (3.4.0)
Requirement already satisfied: packaging in c:\programdata\anaconda3\lib\site-packages (from tensorflow) (25.0)
Requirement already satisfied: protobuf<8.0.0,>=6.31.1 in c:\users\user\appdata\roaming\python\python313\site-packages (from tensorflow) (7.35.1)
Requirement already satisfied: requests<3,>=2.21.0 in c:\programdata\anaconda3\lib\site-packages (from tensorflow) (2.32.5)
Requirement already satisfied: setuptools in c:\programdata\anaconda3\lib\site-packages (from tensorflow) (80.9.0)
Requirement already satisfied: six>=1.12.0 in c:\programdata\anaconda3\lib\site-packages (from tensorflow) (1.17.0)
Requirement already satisfied: termcolor>=1.1.0 in c:\users\user\appdata\roaming\python\python313\site-packages (from tensorflow) (3.3.0)
Requirement already satisfied: typing_extensions>=3.6.6 in c:\programdata\anaconda3\lib\site-packages (from tensorflow) (4.15.0)
Requirement already satisfied: wrapt>=1.11.0 in c:\programdata\anaconda3\lib\site-packages (from tensorflow) (1.17.0)
Requirement already satisfied: grpcio<2.0,>=1.24.3 in c:\users\user\appdata\roaming\python\python313\site-packages (from tensorflow) (1.82.1)
Requirement already satisfied: keras>=3.12.0 in c:\users\user\appdata\roaming\python\python313\site-packages (from tensorflow) (3.15.0)
Requirement already satisfied: numpy>=1.26.0 in c:\programdata\anaconda3\lib\site-packages (from tensorflow) (2.3.5)
Requirement already satisfied: h5py<3.15.0,>=3.11.0 in c:\users\user\appdata\roaming\python\python313\site-packages (from tensorflow) (3.14.0)
Requirement already satisfied: ml_dtypes<1.0.0,>=0.5.1 in c:\users\user\appdata\roaming\python\python313\site-packages (from tensorflow) (0.5.4)
Requirement already satisfied: charset_normalizer<4,>=2 in c:\programdata\anaconda3\lib\site-packages (from requests<3,>=2.21.0->tensorflow) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in c:\programdata\anaconda3\lib\site-packages (from requests<3,>=2.21.0->tensorflow) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\programdata\anaconda3\lib\site-packages (from requests<3,>=2.21.0->tensorflow) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in c:\programdata\anaconda3\lib\site-packages (from requests<3,>=2.21.0->tensorflow) (2026.5.20)
Requirement already satisfied: wheel<1.0,>=0.23.0 in c:\programdata\anaconda3\lib\site-packages (from astunparse>=1.6.0->tensorflow) (0.45.1)
Requirement already satisfied: rich in c:\programdata\anaconda3\lib\site-packages (from keras>=3.12.0->tensorflow) (14.2.0)
Requirement already satisfied: namex in c:\users\user\appdata\roaming\python\python313\site-packages (from keras>=3.12.0->tensorflow) (0.1.0)
Requirement already satisfied: optree in c:\users\user\appdata\roaming\python\python313\site-packages (from keras>=3.12.0->tensorflow) (0.19.1)
Requirement already satisfied: markdown-it-py>=2.2.0 in c:\programdata\anaconda3\lib\site-packages (from rich->keras>=3.12.0->tensorflow) (2.2.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in c:\programdata\anaconda3\lib\site-packages (from rich->keras>=3.12.0->tensorflow) (2.19.2)
Requirement already satisfied: mdurl~=0.1 in c:\programdata\anaconda3\lib\site-packages (from markdown-it-py>=2.2.0->rich->keras>=3.12.0->tensorflow) (0.1.2)

In [8]:
import sys
print(sys.version)

import tensorflow as tf
print(tf.__version__)
print(tf.config.list_physical_devices('GPU'))

3.13.9 | packaged by Anaconda, Inc. | (main, Oct 21 2025, 19:09:58) [MSC v.1929 64 bit (AMD64)]
2.21.0
[]

In [9]:
import tensorflow as tf
print(tf.__version__)

2.21.0

In [10]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [11]:
df = pd.read_csv(r"C:\Users\User\OneDrive\Desktop\Churn_Modelling.csv")
df.head()

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

# it is a binary classification problem

In [12]:
x = df.iloc[: , 3:13]
y = df.iloc[: ,13]

In [13]:
x.head()

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary
0,619,France,Female,42,2,0.00,1,1,1,101348.88
1,608,Spain,Female,41,1,83807.86,1,0,1,112542.58
2,502,France,Female,42,8,159660.80,3,1,0,113931.57
3,699,France,Female,39,1,0.00,2,0,0,93826.63
4,850,Spain,Female,43,2,125510.82,1,1,1,79084.10

In [14]:
y

0       1
1       0
2       1
3       0
4       0
       ..
9995    0
9996    0
9997    1
9998    1
9999    0
Name: Exited, Length: 10000, dtype: int64

# in that categorical features we can fix it now using one hot encoding

feature engineering part

In [15]:
geography = pd.get_dummies(x['Geography'], dtype = int , drop_first = True)
geography

      Germany  Spain
0           0      0
1           0      1
2           0      0
3           0      0
4           0      1
...       ...    ...
9995        0      0
9996        0      0
9997        0      0
9998        1      0
9999        0      0

[10000 rows x 2 columns]

In [16]:
gender  = pd.get_dummies(x['Gender'] ,dtype = int, drop_first = True )
gender

      Male
0        0
1        0
2        0
3        0
4        0
...    ...
9995     1
9996     1
9997     0
9998     1
9999     0

[10000 rows x 1 columns]

concatenate these variables with dataframes

In [17]:
x = x.drop(['Geography','Gender'], axis = 1)

In [18]:
x.head()

,CreditScore,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary
0,619,42,2,0.00,1,1,1,101348.88
1,608,41,1,83807.86,1,0,1,112542.58
2,502,42,8,159660.80,3,1,0,113931.57
3,699,39,1,0.00,2,0,0,93826.63
4,850,43,2,125510.82,1,1,1,79084.10

In [19]:
x1 = pd.concat([x, geography , gender], axis = 1)
x1

,CreditScore,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Germany,Spain,Male
0,619,42,2,0.00,1,1,1,101348.88,0,0,0
1,608,41,1,83807.86,1,0,1,112542.58,0,1,0
2,502,42,8,159660.80,3,1,0,113931.57,0,0,0
3,699,39,1,0.00,2,0,0,93826.63,0,0,0
4,850,43,2,125510.82,1,1,1,79084.10,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...
9995,771,39,5,0.00,2,1,0,96270.64,0,0,1
9996,516,35,10,57369.61,1,1,1,101699.77,0,0,1
9997,709,36,7,0.00,1,0,1,42085.58,0,0,0
9998,772,42,3,75075.31,2,1,0,92888.52,1,0,1
9999,792,28,4,130142.79,1,1,0,38190.78,0,0,0

so we are doing for to handle the catagorical features

splitting the dataset into training set and test set

In [20]:
from sklearn.model_selection import train_test_split

In [21]:
x_train , x_test , y_train , y_test = train_test_split(x1 , y , test_size = 0.2 , random_state = 0)

# it is based on the z score it is used

In [22]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.transform(x_test)

In [23]:
x_train.shape

(8000, 11)

In [24]:
x_test

array([[-0.55204276, -0.36890377,  1.04473698, ...,  1.75486502,
        -0.57369368, -1.09168714],
       [-1.31490297,  0.10961719, -1.031415  , ..., -0.5698444 ,
        -0.57369368, -1.09168714],
       [ 0.57162971,  0.30102557,  1.04473698, ..., -0.5698444 ,
         1.74309049, -1.09168714],
       ...,
       [-0.74791227, -0.27319958, -1.37744033, ..., -0.5698444 ,
         1.74309049,  0.91601335],
       [-0.00566991, -0.46460796, -0.33936434, ...,  1.75486502,
        -0.57369368,  0.91601335],
       [-0.79945688, -0.84742473,  1.04473698, ...,  1.75486502,
        -0.57369368,  0.91601335]], shape=(2000, 11))

 due to data leakage we use separate fit transforem in training and transform  in testing

# to create the ANN

In [25]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.layers import LeakyReLU , PReLU , ELU, ReLU
from tensorflow.keras.layers import Dropout

# lets initialize the ANN

In [26]:
classifier = Sequential()

In [27]:
# adding the input layers

In [63]:
classifier.add(Dense(units = 11, activation = 'relu'))

In [64]:
# adding the  first hidden layer

In [65]:
classifier.add(Dense(units = 7 , activation = 'relu'))
classifier.add(Dropout(0.2))

In [66]:
## adding the second hidden layer

In [67]:
classifier.add(Dense(units = 6 , activation = 'relu'))
classifier.add(Dropout(0.3))

In [68]:
## adding the output layer

In [69]:
classifier.add(Dense(1 , activation = 'sigmoid'))

In [70]:
classifier.compile(optimizer = 'adam' , loss = 'binary_crossentropy' , metrics = ['accuracy'])

In [71]:
# adam inbuilt provide the learnig rate if we want to add new learnig rate

In [72]:
import tensorflow
opt = tensorflow.keras.optimizers.Adam(learning_rate = 0.01)

In [73]:
## early stopping  keras

In [74]:
import tensorflow as tf
early_stopping = tf.keras.callbacks.EarlyStopping(
    monitor="val_loss",
    min_delta=0.0001,
    patience=20,
    verbose=1,
    mode="auto",
    baseline=None,
    restore_best_weights=False,
    start_from_epoch=0,
)

In [75]:
# we need to train our neural network

In [76]:
model_history = classifier.fit(x_train , y_train , validation_split = 0.33 , batch_size =10 , epochs = 1000 , callbacks = early_stopping )

Epoch 1/1000
536/536 ━━━━━━━━━━━━━━━━━━━━ 7s 5ms/step - accuracy: 0.8304 - loss: 0.5466 - val_accuracy: 0.8512 - val_loss: 0.4087
Epoch 2/1000
536/536 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - accuracy: 0.8347 - loss: 0.4412 - val_accuracy: 0.8501 - val_loss: 0.3941
Epoch 3/1000
536/536 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - accuracy: 0.8315 - loss: 0.4266 - val_accuracy: 0.8535 - val_loss: 0.3729
Epoch 4/1000
536/536 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - accuracy: 0.8487 - loss: 0.3996 - val_accuracy: 0.8485 - val_loss: 0.3704
Epoch 5/1000
536/536 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - accuracy: 0.8451 - loss: 0.3878 - val_accuracy: 0.8516 - val_loss: 0.3733
Epoch 6/1000
536/536 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - accuracy: 0.8440 - loss: 0.3879 - val_accuracy: 0.8493 - val_loss: 0.3665
Epoch 7/1000
536/536 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - accuracy: 0.8475 - loss: 0.3846 - val_accuracy: 0.8508 - val_loss: 0.3690
Epoch 8/1000
536/536 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - accuracy: 0.8474 - loss: 0.3766 - val_accuracy: 0.8527 - val_loss: 0.3680
Epoch 9/1000
536/536 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - accuracy: 0.8489 - loss: 0.3718 - val_accuracy: 0.8478 - val_loss: 0.3657
Epoch 10/1000
536/536 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - accuracy: 0.8475 - loss: 0.3756 - val_accuracy: 0.8501 - val_loss: 0.3658
Epoch 11/1000
536/536 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - accuracy: 0.8453 - loss: 0.3824 - val_accuracy: 0.8451 - val_loss: 0.3682
Epoch 12/1000
536/536 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - accuracy: 0.8494 - loss: 0.3742 - val_accuracy: 0.8448 - val_loss: 0.3689
Epoch 13/1000
536/536 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - accuracy: 0.8492 - loss: 0.3722 - val_accuracy: 0.8436 - val_loss: 0.3757
Epoch 14/1000
536/536 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - accuracy: 0.8446 - loss: 0.3739 - val_accuracy: 0.8485 - val_loss: 0.3664
Epoch 15/1000
536/536 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - accuracy: 0.8492 - loss: 0.3676 - val_accuracy: 0.8470 - val_loss: 0.3682
Epoch 16/1000
536/536 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - accuracy: 0.8434 - loss: 0.3728 - val_accuracy: 0.8425 - val_loss: 0.3688
Epoch 17/1000
536/536 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - accuracy: 0.8489 - loss: 0.3689 - val_accuracy: 0.8516 - val_loss: 0.3669
Epoch 18/1000
536/536 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - accuracy: 0.8444 - loss: 0.3683 - val_accuracy: 0.8436 - val_loss: 0.3687
Epoch 19/1000
536/536 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - accuracy: 0.8440 - loss: 0.3693 - val_accuracy: 0.8474 - val_loss: 0.3662
Epoch 20/1000
536/536 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - accuracy: 0.8442 - loss: 0.3727 - val_accuracy: 0.8451 - val_loss: 0.3662
Epoch 21/1000
536/536 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - accuracy: 0.8500 - loss: 0.3651 - val_accuracy: 0.8421 - val_loss: 0.3693
Epoch 22/1000
536/536 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - accuracy: 0.8498 - loss: 0.3655 - val_accuracy: 0.8470 - val_loss: 0.3649
Epoch 23/1000
536/536 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - accuracy: 0.8485 - loss: 0.3687 - val_accuracy: 0.8459 - val_loss: 0.3688
Epoch 24/1000
536/536 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - accuracy: 0.8472 - loss: 0.3691 - val_accuracy: 0.8391 - val_loss: 0.3769
Epoch 25/1000
536/536 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - accuracy: 0.8431 - loss: 0.3701 - val_accuracy: 0.8474 - val_loss: 0.3655
Epoch 26/1000
536/536 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - accuracy: 0.8487 - loss: 0.3623 - val_accuracy: 0.8429 - val_loss: 0.3727
Epoch 27/1000
536/536 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - accuracy: 0.8485 - loss: 0.3611 - val_accuracy: 0.8538 - val_loss: 0.3648
Epoch 28/1000
536/536 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - accuracy: 0.8444 - loss: 0.3686 - val_accuracy: 0.8413 - val_loss: 0.3711
Epoch 29/1000
536/536 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - accuracy: 0.8502 - loss: 0.3665 - val_accuracy: 0.8436 - val_loss: 0.3693
Epoch 30/1000
536/536 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - accuracy: 0.8453 - loss: 0.3659 - val_accuracy: 0.8402 - val_loss: 0.3733
Epoch 31/1000
536/536 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - accuracy: 0.8494 - loss: 0.3630 - val_accuracy: 0.8398 - val_loss: 0.3712
Epoch 32/1000
536/536 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - accuracy: 0.8455 - loss: 0.3691 - val_accuracy: 0.8451 - val_loss: 0.3670
Epoch 33/1000
536/536 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - accuracy: 0.8451 - loss: 0.3654 - val_accuracy: 0.8417 - val_loss: 0.3695
Epoch 34/1000
536/536 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - accuracy: 0.8451 - loss: 0.3627 - val_accuracy: 0.8379 - val_loss: 0.3752
Epoch 35/1000
536/536 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - accuracy: 0.8483 - loss: 0.3619 - val_accuracy: 0.8463 - val_loss: 0.3683
Epoch 36/1000
536/536 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - accuracy: 0.8462 - loss: 0.3583 - val_accuracy: 0.8440 - val_loss: 0.3667
Epoch 37/1000
536/536 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - accuracy: 0.8449 - loss: 0.3670 - val_accuracy: 0.8440 - val_loss: 0.3696
Epoch 38/1000
536/536 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - accuracy: 0.8451 - loss: 0.3616 - val_accuracy: 0.8398 - val_loss: 0.3721
Epoch 39/1000
536/536 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - accuracy: 0.8477 - loss: 0.3602 - val_accuracy: 0.8448 - val_loss: 0.3698
Epoch 40/1000
536/536 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - accuracy: 0.8466 - loss: 0.3599 - val_accuracy: 0.8497 - val_loss: 0.3642
Epoch 41/1000
536/536 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - accuracy: 0.8489 - loss: 0.3630 - val_accuracy: 0.8451 - val_loss: 0.3663
Epoch 42/1000
536/536 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - accuracy: 0.8479 - loss: 0.3605 - val_accuracy: 0.8413 - val_loss: 0.3754
Epoch 43/1000
536/536 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - accuracy: 0.8503 - loss: 0.3601 - val_accuracy: 0.8421 - val_loss: 0.3743
Epoch 44/1000
536/536 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - accuracy: 0.8533 - loss: 0.3585 - val_accuracy: 0.8334 - val_loss: 0.3825
Epoch 45/1000
536/536 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - accuracy: 0.8477 - loss: 0.3648 - val_accuracy: 0.8429 - val_loss: 0.3676
Epoch 46/1000
536/536 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - accuracy: 0.8492 - loss: 0.3593 - val_accuracy: 0.8395 - val_loss: 0.3736
Epoch 47/1000
536/536 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - accuracy: 0.8545 - loss: 0.3573 - val_accuracy: 0.8376 - val_loss: 0.3701
Epoch 48/1000
536/536 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - accuracy: 0.8565 - loss: 0.3546 - val_accuracy: 0.8436 - val_loss: 0.3696
Epoch 49/1000
536/536 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - accuracy: 0.8556 - loss: 0.3580 - val_accuracy: 0.8451 - val_loss: 0.3651
Epoch 50/1000
536/536 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - accuracy: 0.8561 - loss: 0.3521 - val_accuracy: 0.8429 - val_loss: 0.3698
Epoch 51/1000
536/536 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - accuracy: 0.8548 - loss: 0.3515 - val_accuracy: 0.8429 - val_loss: 0.3674
Epoch 52/1000
536/536 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - accuracy: 0.8550 - loss: 0.3515 - val_accuracy: 0.8421 - val_loss: 0.3660
Epoch 53/1000
536/536 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - accuracy: 0.8584 - loss: 0.3484 - val_accuracy: 0.8425 - val_loss: 0.3712
Epoch 54/1000
536/536 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - accuracy: 0.8584 - loss: 0.3528 - val_accuracy: 0.8444 - val_loss: 0.3667
Epoch 55/1000
536/536 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - accuracy: 0.8563 - loss: 0.3495 - val_accuracy: 0.8451 - val_loss: 0.3670
Epoch 56/1000
536/536 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - accuracy: 0.8552 - loss: 0.3524 - val_accuracy: 0.8455 - val_loss: 0.3682
Epoch 57/1000
536/536 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - accuracy: 0.8602 - loss: 0.3455 - val_accuracy: 0.8402 - val_loss: 0.3726
Epoch 58/1000
536/536 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - accuracy: 0.8576 - loss: 0.3538 - val_accuracy: 0.8425 - val_loss: 0.3691
Epoch 59/1000
536/536 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - accuracy: 0.8543 - loss: 0.3479 - val_accuracy: 0.8436 - val_loss: 0.3682
Epoch 60/1000
536/536 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - accuracy: 0.8582 - loss: 0.3536 - val_accuracy: 0.8368 - val_loss: 0.3792
Epoch 60: early stopping

In [77]:
model_history.history.keys()

dict_keys(['accuracy', 'loss', 'val_accuracy', 'val_loss'])

In [78]:
y_pred = classifier.predict(x_test)
y_pred = (y_pred >=0.5)

63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step

In [79]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test , y_pred)
cm

array([[1577,   18],
       [ 296,  109]])

In [80]:
## calucate the accuracy

In [81]:
from sklearn.metrics import accuracy_score
score = accuracy_score(y_pred , y_test)

In [82]:
score

0.843

In [83]:
# get the weights

In [84]:
classifier.get_weights()

[array([[-1.63889736e-01, -2.30286550e-02, -2.60291159e-01,
         -1.32023320e-02, -7.51799047e-02,  3.27950656e-01,
          1.35303900e-01,  1.06962867e-01,  2.45176762e-01,
          1.80317476e-01,  1.81560189e-01],
        [ 5.57404570e-02,  1.90270334e-01,  1.12583697e+00,
         -9.11309183e-01,  3.30471218e-01,  9.34493959e-01,
         -2.00692434e-02, -9.49555039e-01,  4.57344264e-01,
          1.88866302e-01, -1.98051840e-01],
        [-2.30777562e-01, -2.54865829e-02, -2.59240896e-01,
          2.96028882e-01,  1.17983306e-02,  2.71839648e-01,
          2.89938986e-01,  4.41364981e-02,  2.58191794e-01,
          2.89940666e-02,  4.76574481e-01],
        [-5.68652272e-01,  4.94385481e-01, -7.39514887e-01,
          2.71856338e-01, -6.47450984e-02, -5.60305119e-01,
         -4.10794392e-02,  1.67799681e-01, -1.14916541e-01,
          9.56425130e-01, -8.09778512e-01],
        [-1.34136462e+00,  9.73586202e-01,  3.31450909e-01,
         -3.92691791e-01,  3.46165746e-01,  3.31117570e-01,
         -5.76529324e-01,  2.39486709e-01,  1.07626438e+00,
         -5.63223004e-01, -1.57880664e-01],
        [ 2.16303140e-01, -4.39935923e-02, -2.95449048e-01,
          2.20368117e-01,  5.63943624e-01, -1.24434151e-01,
         -1.35434613e-01, -8.99396837e-02,  1.36248348e-02,
          7.14356154e-02, -3.21318626e-01],
        [-4.39072967e-01, -4.76735026e-01, -1.92748278e-01,
          2.99403965e-01,  4.64306027e-01,  1.21181734e-01,
         -4.50751781e-01, -4.18184638e-01, -3.06487679e-01,
          1.17529333e-02,  3.36930186e-01],
        [ 6.58406392e-02,  7.38972216e-04, -4.58378434e-01,
          9.87685323e-02,  2.83205271e-01,  3.59034628e-01,
          2.76438266e-01, -1.45360515e-01,  1.07964717e-01,
         -1.12895578e-01,  3.37047309e-01],
        [ 1.73196554e-01, -6.42129958e-01,  4.99986708e-01,
          2.35604554e-01,  7.66976830e-03, -4.31942374e-01,
          2.97569126e-01, -3.83298814e-01,  1.87216133e-01,
         -1.20876342e-01, -1.33169979e-01],
        [ 8.11316594e-02, -8.42574388e-02, -9.48100686e-02,
          4.01355147e-01,  1.55994315e-02,  2.05852136e-01,
          9.14570391e-02, -2.39966214e-01, -8.81522819e-02,
         -6.94635808e-01, -5.46770692e-01],
        [ 2.68209487e-01,  3.06011401e-02,  6.82888269e-01,
          2.46196106e-01,  5.45307517e-01, -1.96209282e-01,
         -4.77512807e-01,  1.61053956e-01,  1.34629026e-01,
          1.09705001e-01,  9.73010242e-01]], dtype=float32),
 array([-0.06883078, -0.35466966, -0.05686296,  0.12828813,  0.2972556 ,
         0.13409844, -0.12675944,  1.0800958 , -0.41366997, -0.47421867,
        -0.30513576], dtype=float32),
 array([[ 0.45559728, -0.44910237,  0.59854597, -0.95265   , -0.06356942,
          0.207553  , -0.49576688],
        [ 0.12415622,  0.290689  ,  0.7445209 ,  0.37917876, -1.597323  ,
          0.2213305 , -0.57951987],
        [-0.40369675, -0.80206126,  0.29362154,  0.3326461 , -2.0527456 ,
         -0.08473579,  0.5922835 ],
        [ 0.03592502, -1.0404507 , -0.18234032,  0.4061605 , -0.23501693,
         -2.3906085 , -0.10874253],
        [ 0.06409141, -1.9342713 , -0.11097162,  0.2256299 , -0.75294024,
          0.00917583,  0.42269182],
        [-0.36647025,  0.30181417,  0.04005795, -0.1623585 , -2.0451667 ,
          0.48479024,  0.7917153 ],
        [ 0.04023268, -0.05457848,  0.44207206, -0.678603  , -0.13594303,
         -0.32311174, -0.4971434 ],
        [ 0.00348658, -0.3908603 , -0.7794151 , -0.05079185,  0.5236793 ,
         -0.5377834 ,  0.53942174],
        [-0.07107881, -1.1679453 , -0.98031104,  0.49970794, -0.7711634 ,
          0.49396253, -0.45683545],
        [-0.39295182, -0.4691182 ,  0.12627181, -0.94074726, -1.5640271 ,
         -0.91274244, -0.13570318],
        [ 0.1596746 , -1.36002   ,  0.54613066, -1.0016415 , -3.1196027 ,
          0.07997923,  0.11593112]], dtype=float32),
 array([ 0.87571615,  0.01034766,  0.22848691, -0.30167747, -0.27066505,
        -0.10049154,  0.34995   ], dtype=float32),
 array([[-0.669914  ,  0.81940424, -0.7087709 ,  0.7002987 , -0.2107143 ,
          0.13244593],
        [-0.14438316, -1.8939822 ,  2.1105003 , -0.43085316, -1.0185213 ,
         -1.5768799 ],
        [-0.376719  , -0.39636928,  0.24892484, -0.21826775, -0.4009309 ,
         -0.40713516],
        [-0.6620878 , -0.14747128,  1.2242876 , -0.11819672, -0.01969589,
          0.00693998],
        [ 0.28722098, -0.9967393 , -0.9777187 , -1.103677  , -0.9241152 ,
         -1.1977141 ],
        [-0.17792068, -0.04360576,  0.50824136, -0.83716017, -0.18453912,
         -0.21144705],
        [ 0.01292618,  0.35661355, -0.03511599, -0.23786978,  0.55894357,
          0.8763686 ]], dtype=float32),
 array([-0.17881738,  0.6505467 ,  0.10062253,  0.9599331 ,  0.6793199 ,
         0.45981148], dtype=float32),
 array([[ 0.06391811],
        [-0.43415567],
        [ 1.428722  ],
        [-0.80303717],
        [-1.015924  ],
        [-1.0106738 ]], dtype=float32),
 array([0.48090965], dtype=float32),
 array([[ 0.92886347,  1.1128931 , -0.45798904, -0.67763585, -0.47826624,
         -0.4078849 , -0.47335696, -0.36726695,  1.0482624 ,  1.1551247 ,
          1.117178  ]], dtype=float32),
 array([-0.01910826, -0.03142141,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ,  0.        , -0.01140037, -0.02346949,
        -0.00656733], dtype=float32),
 array([[ 1.23719454e+00, -4.91816282e-01,  4.13290679e-01,
          9.31926221e-02,  2.02514365e-01, -9.06855106e-01,
          1.44616306e-01,  2.70531327e-01,  2.60405928e-01,
          4.18642372e-01,  9.72091779e-02],
        [ 1.10425484e+00, -1.91819936e-01,  5.22339106e-01,
          3.74013692e-01,  6.01108789e-01, -6.57904029e-01,
          1.04596660e-01,  6.41460717e-01,  1.72155470e-01,
          1.46853536e-01, -1.21629608e+00],
        [-2.36675650e-01, -2.35080719e-04, -4.36705261e-01,
         -4.71809387e-01,  4.25283194e-01,  3.12898755e-02,
         -1.22519135e-02,  3.13899636e-01, -9.77399945e-02,
          9.07862186e-02,  1.93466783e-01],
        [ 4.22014475e-01, -1.01499707e-01,  9.39941406e-03,
         -1.06945544e-01,  7.86289573e-02, -2.20306307e-01,
         -4.45859492e-01, -2.95241952e-01,  2.86944568e-01,
         -1.19581819e-02, -8.23194385e-02],
        [ 5.22003472e-01, -1.41948164e-01, -3.50652516e-01,
          1.07459366e-01,  1.44006670e-01, -1.43376678e-01,
          2.47404158e-01, -2.80842483e-01, -2.48331279e-01,
         -2.78068662e-01, -3.01240444e-01],
        [ 4.99439061e-01, -1.47880822e-01,  1.07127428e-01,
          2.26752818e-01, -1.42216682e-02, -1.90099061e-01,
         -2.73550034e-01,  8.05587173e-02, -1.27485991e-02,
          5.60629368e-03, -4.47215289e-01],
        [-4.83381569e-01, -1.11126840e-01,  1.99828804e-01,
         -4.03029263e-01, -7.81487226e-02, -3.64278525e-01,
          3.34651589e-01, -7.85147846e-02,  3.73471320e-01,
          2.20323861e-01,  2.69045532e-01],
        [-4.90628809e-01,  1.45441771e-01, -1.18633032e-01,
          2.58195221e-01,  3.42822433e-01, -2.97013342e-01,
          4.06413436e-01,  1.28985047e-02,  4.14242625e-01,
          4.48272347e-01,  2.00113416e-01],
        [ 9.04424071e-01, -3.66886646e-01,  9.31384087e-01,
          4.94775057e-01,  2.69498974e-01, -1.07522321e+00,
          2.06922114e-01, -6.55076206e-01,  1.09607756e-01,
         -1.24485195e+00,  2.00715020e-01],
        [ 2.95845926e-01, -2.84335732e-01,  9.44997191e-01,
         -1.98493755e+00,  8.24193358e-01, -8.74638438e-01,
         -2.87661344e-01,  1.35293201e-01,  6.42768085e-01,
         -8.57899845e-01,  2.11029202e-01],
        [ 6.75205827e-01,  1.74333248e-02,  4.37940061e-01,
          3.65932643e-01,  3.46376270e-01, -1.21532524e+00,
         -3.94541323e-02,  1.32338062e-01, -5.27224243e-01,
         -4.14740086e-01,  2.01900169e-01]], dtype=float32),
 array([ 0.01006051, -0.101679  ,  0.00906554,  0.10059069,  0.02668427,
         0.2518656 ,  0.35593572, -0.01301977, -0.00556771,  0.17959373,
         0.08942042], dtype=float32),
 array([[ 0.5524727 , -0.8495942 , -1.4493134 , -0.18226728, -0.53792346,
          0.17569935, -0.28888732],
        [-0.48539084, -0.1963178 , -0.46298975, -0.16509067,  0.2629221 ,
         -0.10491746,  0.34948784],
        [ 0.4263527 , -1.0416982 , -1.5536628 ,  0.33485588, -0.5875884 ,
         -0.16236433, -0.01199985],
        [-0.00673524, -0.33293808,  0.16866343,  1.0542023 , -0.44835398,
          0.16307564, -0.07514822],
        [-0.45396855, -0.45510495, -1.2902195 ,  0.48703656, -0.2960651 ,
         -0.18137531, -0.3433293 ],
        [-0.5968266 ,  0.6117729 ,  0.8545485 , -0.17422609,  0.43291804,
          0.24607095,  0.0870185 ],
        [-0.47886232,  0.22544132, -0.14002524, -0.35006794,  0.63570046,
         -0.31998903, -0.14587936],
        [ 0.15586457, -0.8828998 , -0.9102259 ,  0.4713768 ,  0.06571509,
         -0.5605674 , -0.2672627 ],
        [-0.22429173, -0.04098571, -1.0271544 ,  0.55665237, -0.39756238,
         -0.27566564, -0.5316954 ],
        [-0.09832091,  0.54918176,  0.39453134,  1.0499561 ,  0.36102483,
         -0.11933511,  0.12587552],
        [ 0.20422876,  0.14797157,  0.47158453,  0.9505916 ,  0.38654995,
         -0.21315025, -0.521043  ]], dtype=float32),
 array([-1.10748574e-01,  1.72900647e-01,  1.30797759e-01, -3.54088724e-01,
         2.62926668e-01, -1.66393263e-04, -1.27281677e-02], dtype=float32),
 array([[ 0.42069775, -0.16665122, -0.36290064,  0.66811424, -0.07761174,
         -0.09884408],
        [-0.2599279 ,  0.85599047, -0.11622506, -2.2286572 , -0.2205289 ,
          0.79815835],
        [-0.4125311 ,  1.2844142 , -1.0150614 , -1.9911587 , -0.13706005,
          1.3046399 ],
        [ 0.5923667 , -1.1585711 ,  1.1250278 ,  0.13274953, -0.16256279,
         -0.78317744],
        [-0.1498509 ,  0.4574446 ,  0.02942743, -0.8422299 , -0.35676372,
          0.32969996],
        [-0.00436532, -0.09815833,  0.2122562 ,  0.60362387, -0.08927965,
          0.1893324 ],
        [ 0.47914147, -0.51941156, -0.34450847,  0.09062064,  0.66936386,
          0.11028041]], dtype=float32),
 array([ 0.07187632,  0.0368242 , -0.04495741,  0.3121768 ,  0.        ,
         0.03310849], dtype=float32),
 array([[ 0.96978056],
        [-0.714427  ],
        [ 0.8153282 ],
        [ 0.8782518 ],
        [ 0.7428124 ],
        [-0.8473078 ]], dtype=float32),
 array([-1.4267268], dtype=float32)]